# yaml-language-server: $schema=https://json.schemastore.org/lazydocker.json
gui:
  border: "single"
  theme:
    activeBorderColor:
      - "#ff9e64"
      - "bold"
    inactiveBorderColor:
      - "#27a1b9"
    optionsTextColor:
      - "#7aa2f7"
    selectedLineBgColor:
      - "#283457"
commandTemplates:
  dockerCompose: "docker compose"
