keymap_mode = "vim-insert"
keymap_cursor = { emacs = "blink-block", vim_insert = "blink-bar", vim_normal = "steady-block" }
theme = "tokyonight-night"

[sync]
records = true

[daemon]
enabled = true
socket_path = "/run/user/1000/atuin.sock"
