# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

palette = 'tokyonight_night'

format = """
$directory\
$git_branch\
$character"""

right_format = """
$git_status\
$bun\
$c\
$cmake\
$nodejs\
$rust\
$golang\
$php\
$python\
$zig\
"""

# Inserts a blank line between shell prompts
add_newline = false

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[➜](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'
error_symbol = "[!](bold red)"

[directory]
style = "fg:text"
format = "[ $path ]($style)"
truncation_length = 1
# truncation_symbol = "…/"

[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = " "
format = '[$symbol$branch](fg:blue) '

[git_status]
style = "green"
conflicted = " "
ahead = " "
behind = " "
diverged = " "
untracked = " "
stashed = " "
modified = " "
staged = " "
renamed = " "
deleted = " "
format = '[($ahead_behind$conflicted $untracked$modified$renamed$typechanged$deleted$staged$stashed)]($style)'

[bun]
symbol = " "
format = '[ $symbol$version](fg:#fbf0df)'

[c]
symbol = " "
format = '[ $symbol$version(-$name)](fg:#5e76bf)'

[cmake]
symbol = "󰔷 "
format = '[ $symbol$version](fg:#0bd904)'

[golang]
symbol = " "
format = '[ $symbol$version](fg:#00add8)'

[nodejs]
symbol = " "
format = '[ $symbol$version](fg:#f0db4f)'

[php]
symbol = " "
format = '[ $symbol$version](fg:#777bb3)'

[python]
symbol = " "
format = "[ ${symbol}${pyenv_prefix}(${version} )(\\($virtualenv\\) )](fg:#ffde57)"

[rust]
symbol = " "
format = '[ $symbol$version](fg:#ce422b)'

[zig]
symbol = " "
format = '[ $symbol$version](fg:#f7a41d)'

# palette tables should be last in the config
[palettes.tokyonight_night]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f7768e"
maroon = "#db4b4b"
peach = "#fab387"
yellow = "#e0af68"
green = "#9ece6a"
teal = "#1abc9c"
sky = "#7dcfff"
sapphire = "#89ddff"
blue = "#7aa2f7"
lavender = "#b4befe"
text = "#c0caf5"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1a1b26"
mantle = "#16161e"
crust = "#11111b"
